README.md, dashtx.js, package-lock.json, package.json
Current standard practice is to salt the signatures such that they end up different every time - even when signing the exact same bytes twice in a row.
=> fix(sign): use extra entropy

README.md
`units` is not the correct key, it seems. 
Fixes: 
```
/home/foobar/code/DashJoin.js/node_modules/dashtx/dashtx.js:461
throw new Error(`every output must have 'satoshis'`);
^
Error: every output must have 'satoshis'
at /home/foobar/code/DashJoin.js/node_modules/dashtx/dashtx.js:461:15
at Array.forEach (<anonymous>)
at Object.Tx._create (/home/foobar/code/DashJoin.js/node_modules/dashtx/dashtx.js:459:13)
at Object.Tx.createHashable (/home/foobar/code/DashJoin.js/node_modules/dashtx/dashtx.js:351:18)
at Object.Tx._hashAndSignAll (/home/foobar/code/DashJoin.js/node_modules/dashtx/dashtx.js:251:27)
at Object.hashAndSignAll (/home/foobar/code/DashJoin.js/node_modules/dashtx/dashtx.js:144:23)
at demo (/home/foobar/code/DashJoin.js/src/tx-dashcore-lib.js:50:29)
at …
```
=> fix: replace "units" with "satoshis" to prevent exception

README.md, dashtx.js, package-lock.json, package.json, tests/hash-and-sign-all.js, tests/legacy-tx.js, tests/lex-sort.js, tests/memo.js
Well, that was dumb.
I mean, I did fix a bug, but the maximum memo length only went up from 75 bytes to 80 bytes so... 🤷‍♀️
(it didn't actually support 83 bytes - that number includes the opcode and size bytes)
=> fix(memo): correct byte lengths, output count, and support donation to the network

README.md, dashtx.js, package-lock.json, package.json
Due to the nature of sorting inputs and outputs, the `keys` array will need to be deprecated and replaced with a local `getPrivateKey()` option.
The reason we don't allow private keys directly on the `input` object is that  they've very likely to be logged when debugging, etc, and we don't want the keys showing up in the logs.
```diff
-  let keys = [addressKey.privateKey];
-  let txInfoSigned = await dashTx.hashAndSignAll(txInfo, keys);
+  let signOpts = {
+    getPrivateKey: function (input, i) {
+      // look up a private key by the address, pubKeyHash, or pubkey of input
+      return addressKey.privateKey;
+    },
+  };
+  let txInfoSigned = await dashTx.hashAndSignAll(txInfo, signOpts);
```
=> doc+ref: document createLegacyTx() and add signOpts.getPrivateKey

dashtx.js, package-lock.json, package.json
`createSigned` inside of `Tx._hashAndSignAll` was not passing the version provided in the `txInfo` param and therefor could not adjust the version.
This is required if wanting to use DashTx.js with other cryptocurrencies.
=> add `version` to `txInfoSigned`

dashtx.js
Also fixes https://github.com/dashhive/DashTx.js/issues/32
=> chore: various lint fixes

dashtx.js
=> ref: split appraise into component parts

dashtx.js, package-lock.json, package.json
reverts 7e870a484bf7af1c6db6d2f30fd55fadb7c0c19b (published in v0.14.0)
`hashAndSignAll()`, which has multiple async handoffs, needs its own, scoped copy of the key utils so that when it is called concurrently, each call gets its own, correct key-map function. 
This time more explicit - and a comment - so that I don't pull a stupid like that again.
=> fix: scope keyUtils to hashAndSignAll lifecycle

dashtx.mjs, package.json
Inspecting https://bundlephobia.com/package/dashtx@0.14.1 (and 0.14.0) results in an EntryPointError, this resolves the EntryPointError issue as well as some issues with using the package as an ESM module.
See https://bundlephobia.com/package/dashtx@0.14.2-1 for this code working at bundlephobia.
=> Fix bundlephobia and esm import

dashtx.js
Standardizing on `txId` was a simple matter of confusion since the various APIs use different names and casings for the same values.
Specifically `txId` is from Insight, but all (I think) of Core uses `txid`.
=> fix: accept txid (canonical) or txId (deprecated, from insight)

README.md, dashtx.js, examples/tx.test.js, package-lock.json, package.json, tests/hash-and-sign-all.js, tests/legacy-finalize-presorted.js, tests/memo.js
replaces #47, which was closed by mistake
https://github.com/dashhive/DashTx.js/tree/ref-false-deps
This has caused issues with false positive missing dependency warnings in bundlers, and it's just confusing to look at.
Nixing.
Although this reduces convenience, DashTx isn't meant to be convenient - it's meant to be accurate. Wallet libraries built atop DashTx will make it convenient.
=> ref: ditch confusing dependency injection (corrected)

dashtx.js, index.js, package.json
Marks `txId` as optional and `txid` as required.
```diff
- txId = tx.txid || tx.txId
+ txid = tx.txId || tx.txid
```
=> fix doc and access order of txid

dashtx.js, package-lock.json, package.json
to make it easier to expose what's needed for CoinJoin txes
=> feat: add option to create the sighash tx with the trailing sighash byte

bin/create-memo.js, dashtx.js, package-lock.json, package.json, tests/legacy-draft.js, tests/legacy-finalize-presorted.js, tests/memo.js
In the simplest case, having a `keys` array rather than a `getPrivateKey()` method _seems_ more convenient.
However, beyond any simple test case, trying to track the order of the `keys` array becomes obnoxious and error prone.
The goal for DashTx is not to be a n00b-friendly tx library (no such thing can exist), but it is to make developing wallets easy - and the `getPrivateKey()` function does _much_ better at that.
=> ref! only support `getPrivateKey()`, drop `keys` array

README.md, dashtx.js, index.js
Although legacy software typically sends ALL, ALL+ANYONECANPAY is "required" for Coin Join, and more importantly, it doesn't leak unnecessary information about the transaction characteristics.
Namely, it doesn't dictate that the transaction must have been a single-wallet transaction. Since multi-wallet transactions are supported, there doesn't seem to be any reason to leak that characteristic information.
=> ref: default to ALL + ANYONECANPAY

dashtx.js
Fixes #72. `keyUtils.getPrivateKey` => `keyUtils?.getPrivateKey`
=> fix: use ?. to check if keyUtils.getPrivateKey exists

README.md, dashtx.js, package-lock.json, package.json, tests/rpc-getblockchaininfo.js
No need for insight, DashSight, dashd-rpc, or DashRPC.js.
This is the real deal, right here.
=> feat: include DashTx.utils.rpc(basicAuthUrl, method, arg1, arg2, ...)

dashtx.js, package-lock.json, package.json
- empty strings are now considered valid memos
- `null` is now the placeholder value for objects that complete the output interface
```diff
let outputs = [
-   { satoshis: 10000, memo: '', message: '', address: 'xxxx' },
+   { satoshis: 10000, memo: null, message: null, address: 'xxxx' },
];
```
Previously an output that looked like this would be considered a payment to 'xxx'
```js
let outputs = [
{ satoshis: 10000, memo: '', message: '', address: 'xxxx' },
];
```
Between this and #74 (which allows burn memos), it will now throw an error:
```js
throw new Error(`memo outputs must not have 'address' or 'pubKeyHash'`);
```
Also, it seems that there may have been a regression of #56, because this does the same that that says in the title. …
=> fix!: allow empty memos (NULL op returns)

dashtx.js, package-lock.json, package.json, tests/legacy-tx.js, tests/lex-sort.js
Related to some of what was reviewed here: https://www.youtube.com/watch?v=7TBHmndBx00
It's actually _IMPORTANT_ for the the drafting functions to NOT be `async` - it helps prevent duplicate spend issues and general state management issues (i.e. another process could request the same address).
Here's another summary of the tx lifecycle:
1. _sync_ draftTx
2. (??) reserveFundsInWallet
3. backfill & await signTx
4. await broadcastTx
5. (??) commitWalletState
We want the loop between the draft and the reserve to be as close as possible so that other tasks can't use them, and without having to depend on storage and sync implementation details of the wallet.
=> fix: remove leftover 'async' marker from tx drafting function [READ]

bin/create-memo.js, dashtx.js
Fairy simple updates. Check each commit for a simpler view.
=> add type for TxRPC, rename and fully lint TxKeyUtils

examples/key-utils.js
Adding this example in hopes of reducing the boilerplate a bit more.
This does well to be in its own file anyway.
=> doc: add examples/key-utils.js copy-pasta

dashtx.js, package-lock.json, package.json, tests/parser.js
We need to be able to create Platform TXes. Re: <https://github.com/dashhive/DashPlatform.js/issues/1>
Now we only use 2 bytes for `version`, and the other two for `type`.
We also allow a 'trailer' for AssetLock and AssetUnlock.
Tests updated.
=> feat(platform): split 'version' from 'type', add 'extraPayload', new utils exports

dashtx.js, package-lock.json, package.json
If the version is set to 0, it will be overwritten with the default (3). That turns out to not be right.
```js
version = txInfo.version ?? CURRENT_VERSION.
```
I also updated other semantically incorrect uses of `||` - even when the result doesn't change - to distinguish between _boolean logical operations_ and _default assignment_.
=> fix: use nullish coalescing (to allow version and other values to be 0 or "")
